/** Curated surprise topics — pick locally, then generate an entry. */
export const RANDOM_TOPICS: string[] = [
  "pigeons",
  "queues",
  "volcanoes",
  "passports",
  "moss",
  "elevators",
  "coffee",
  "bureaucracy",
  "container ships",
  "handshakes",
  "thunderstorms",
  "public transport",
  "sleep",
  "concrete",
  "ants",
  "inflation",
  "airports",
  "umbrellas",
  "sidewalks",
  "street food",
  "time zones",
  "libraries",
  "bridges",
  "laundry",
  "mosquitoes",
  "bread",
  "traffic lights",
  "post offices",
  "museums",
  "tides",
  "keys",
  "maps",
  "hotels",
  "transport tickets",
  "fog",
  "stairs",
  "markets",
  "cats in cities",
  "fountains",
  "sunglasses",
  "railway stations",
  "ferries",
  "caves",
  "glaciers",
  "desert heat",
  "mosquito nets",
  "tipping customs",
  "siestas",
  "street signs",
  "public toilets",
  "power sockets",
  "tap water",
  "beaches",
  "national parks",
  "border crossings",
  "currency exchange",
  "luggage",
  "jet lag",
  "street musicians",
  "bicycles",
  "trams",
  "roundabouts",
  "parking",
  "street trees",
  "graffiti",
  "clock towers",
  "lighthouses",
  "harbours",
  "fishing boats",
  "rice fields",
  "olive trees",
  "tea",
  "cheese",
  "spice markets",
  "night trains",
  "camping",
  "hiking boots",
  "compasses",
  "weather forecasts",
  "earthquakes",
  "floods",
  "wildfires",
  "coral reefs",
  "seals",
  "crows",
  "bees",
  "fungi",
  "lichen",
  "river deltas",
  "canals",
  "windmills",
  "skyscrapers",
  "subway etiquette",
  "lost and found",
  "souvenirs",
  "guidebooks",
  "postcards",
  "language barriers",
  "gestures",
  "eye contact",
  "silence in conversation",
  "queuing etiquette",
  "shoes indoors",
];

export function pickRandomTopic(): string {
  const index = Math.floor(Math.random() * RANDOM_TOPICS.length);
  return RANDOM_TOPICS[index] ?? "pigeons";
}
